=== vipatil/javaprojects/investment/src/investment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/investment" xmlns:tns="http://www.example.org/investment" elementFormDefault="qualified">





    <element name="investments" type="tns:investments"></element>
    
    <complexType name="investments">
    	<sequence>
    		<element name="investment" type="tns:investment"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="investment">
    	<sequence>
    		<element name="symbol" type="string"></element>
    		<element name="name" type="string"></element>
    		<element name="transaction" type="tns:transaction" maxOccurs="unbounded" minOccurs="1"></element>
    		<element name="current_value" type="float"></element>
    	</sequence>
    	<attribute name="type">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="equity"></enumeration>
    				<enumeration value="mf"></enumeration>
    				<enumeration value="fd"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="transaction">
    	<sequence>
    		<element name="investment_amount" type="float"></element>
    		<element name="date" type="date"></element>
    		<element name="quantity" type="int"></element>
    		<element name="unit_price" type="float"></element>
    	</sequence>
    </complexType>
</schema>

=== vipatil/javaprojects/investment/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:investments xmlns:tns="http://www.example.org/investment" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/investment investment.xsd ">
  <tns:investment type="equity">
    <tns:symbol>tns:symbol</tns:symbol>
    <tns:name>tns:name</tns:name>
    <tns:transaction>
      <tns:investment_amount>0.0</tns:investment_amount>
      <tns:date>2001-01-01</tns:date>
      <tns:quantity>0</tns:quantity>
      <tns:unit_price>0.0</tns:unit_price>
    </tns:transaction>
    <tns:current_value>0.0</tns:current_value>
  </tns:investment>
</tns:investments>

=== vipatil/javaprojects/investment/idata.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:investments xmlns:tns="http://www.example.org/investment" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/investment src/investment.xsd ">
  <tns:investment type="equity">
    <tns:symbol>MAHABANK</tns:symbol>
    <tns:name>Bank of Maharashtra</tns:name>
    <tns:transaction>
      <tns:investment_amount>0.0</tns:investment_amount>
      <tns:date>2001-01-01</tns:date>
      <tns:quantity>0</tns:quantity>
      <tns:unit_price>0.0</tns:unit_price>
    </tns:transaction>
    <tns:current_value>0.0</tns:current_value>
  </tns:investment>
  <tns:investment type="equity">
    <tns:symbol>GRUH</tns:symbol>
    <tns:name>Gruh Finance Limited</tns:name>
    <tns:transaction>
      <tns:investment_amount>0.0</tns:investment_amount>
      <tns:date>2001-01-01</tns:date>
      <tns:quantity>0</tns:quantity>
      <tns:unit_price>0.0</tns:unit_price>
    </tns:transaction>
    <tns:current_value>0.0</tns:current_value>
  </tns:investment>
  <tns:investment type="equity">
    <tns:symbol>LUPIN</tns:symbol>
    <tns:name>Lupin Limited</tns:name>
    <tns:transaction>
      <tns:investment_amount>0.0</tns:investment_amount>
      <tns:date>2001-01-01</tns:date>
      <tns:quantity>0</tns:quantity>
      <tns:unit_price>0.0</tns:unit_price>
    </tns:transaction>
    <tns:current_value>0.0</tns:current_value>
  </tns:investment>
  <tns:investment type="equity">
    <tns:symbol>FRL</tns:symbol>
    <tns:name>Future Retail Limited</tns:name>
    <tns:transaction>
      <tns:investment_amount>0.0</tns:investment_amount>
      <tns:date>2001-01-01</tns:date>
      <tns:quantity>0</tns:quantity>
      <tns:unit_price>0.0</tns:unit_price>
    </tns:transaction>
    <tns:current_value>0.0</tns:current_value>
  </tns:investment>
  <tns:investment type="equity">
    <tns:symbol>PIDILITIND</tns:symbol>
    <tns:name>Pidilite Industries Limited</tns:name>
    <tns:transaction>
      <tns:investment_amount>0.0</tns:investment_amount>
      <tns:date>2001-01-01</tns:date>
      <tns:quantity>0</tns:quantity>
      <tns:unit_price>0.0</tns:unit_price>
    </tns:transaction>
    <tns:current_value>0.0</tns:current_value>
  </tns:investment>
</tns:investments>
